/*
 * Copyright (c) 2016-2021 Intel Corporation
 *
 * SPDX-License-Identifier: MIT-0
 */
#ifndef __PLL_RESET_MONITOR_REGS_H__
#define __PLL_RESET_MONITOR_REGS_H__

#include <io.h>

#define IORD_PLL_RESET_MONITOR(base)	IORD(base, 0)

#define PLL_RESET_MONITOR_UNLOCK_COUNT_MASK	(0xFF000000)
#define PLL_RESET_MONITOR_UNLOCK_COUNT_OFST	(24)

#define PLL_RESET_MONITOR_LOCK_COUNTER_WIDTH_MASK	(0x00F00000)
#define PLL_RESET_MONITOR_LOCK_COUNTER_WIDTH_OFST	(20)

#define PLL_RESET_MONITOR_CAPTURE_LOCK_COUNT_MASK	(0xFFFFF)
#define PLL_RESET_MONITOR_CAPTURE_LOCK_COUNT_OFST	(0)

#endif /* __PLL_RESET_MONITOR_REGS_H__ */
