/*
 * Copyright (c) 2016-2021 Intel Corporation
 *
 * SPDX-License-Identifier: MIT-0
 */
#ifndef __RESET_DEBOUNCER_REGS_H__
#define __RESET_DEBOUNCER_REGS_H__

#include <io.h>

#define IORD_RESET_DEBOUNCER(base)	IORD(base, 0)

#define RESET_DEBOUNCER_ASSERTION_EDGE_COUNT_MASK	(0xE0000000)
#define RESET_DEBOUNCER_ASSERTION_EDGE_COUNT_OFST	(29)

#define RESET_DEBOUNCER_DEASSERTION_EDGE_COUNT_MASK	(0x1F000000)
#define RESET_DEBOUNCER_DEASSERTION_EDGE_COUNT_OFST	(24)

#define RESET_DEBOUNCER_CAPTURE_DEBOUNCE_COUNT_MASK	(0x00FFFFFF)
#define RESET_DEBOUNCER_CAPTURE_DEBOUNCE_COUNT_OFST	(0)

#endif /* __RESET_DEBOUNCER_REGS_H__ */
