#!/bin/bash
#
# Copyright (c) 2016 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#

#
# This script creates the boot_check application in this directory.


BSP_DIR=../boot_check_bsp
QUARTUS_PROJECT_DIR=../..
NIOS2_APP_GEN_ARGS="\
--set QUARTUS_PROJECT_DIR ${QUARTUS_PROJECT_DIR:?} \
--elf-name boot_check.elf \
--set APP_CFLAGS_OPTIMIZATION -Os \
--set OBJDUMP_INCLUDE_SOURCE 1 \
--src-files boot_check.c \
"

set -x

# is Nios II EDS tools environment present?
[ -z "${SOPC_KIT_NIOS2:?}" ] && {
	set +x
	echo ""
	echo "ERROR: SOPC_KIT_NIOS2 environmental variable must be set"
	echo ""
	exit 1
}

# has the application Makefile already been created?
[ -f ./Makefile ] && {
	set +x
	echo ""
	echo "ERROR: Application Makefile already exists.  Delete Makefile to recreate."
	echo ""
	exit 1
}

# is the BSP project built?
[ -f "${BSP_DIR:?}/public.mk" ] || {
	pushd "${BSP_DIR:?}" >> /dev/null
	./create-this-bsp || {
		set +x
		echo "create-this-bsp failed"
		exit 1
	}
	popd >> /dev/null
}

# create the reset modules assignments header file
sopcinfo2swinfo \
	--input="${QUARTUS_PROJECT_DIR:?}/test_sys.sopcinfo" \
	--output=test_sys.swinfo || {
		set +x
		echo "sopcinfo2swinfo failed"
		exit 1
	}
	
../../scripts/extract_swinfo.sh test_sys.swinfo || {
	set +x
	echo "extract_swinfo.sh failed"
	exit 1
}

# create the application project Makefile
nios2-app-generate-makefile \
	--bsp-dir "${BSP_DIR:?}" \
	${NIOS2_APP_GEN_ARGS:?} || {
		set +x
		echo "nios2-app-generate-makefile failed"
		exit 1
	}

# build application project
make || {
	set +x
	echo "make failed"
	exit 1
}

# create the meminit file for the onchip RAM
make mem_init_generate || {
	set +x
	echo "make mem_init_generate failed"
	exit 1
}

set +x

exit 0

