#!/bin/bash
#
# Copyright (c) 2016-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT-0
#

#
# This script creates the boot_check application in this directory.


BSP_DIR=../boot_check_bsp
QUARTUS_PROJECT_DIR=../..
NIOS2_APP_GEN_ARGS="\
--set QUARTUS_PROJECT_DIR ${QUARTUS_PROJECT_DIR:?} \
--elf-name boot_check.elf \
--set APP_CFLAGS_OPTIMIZATION -Os \
--set OBJDUMP_INCLUDE_SOURCE 1 \
--src-files boot_check.c \
"

set -x

# is Nios II EDS tools environment present?
[ -z "${SOPC_KIT_NIOS2:?}" ] && {
	set +x
	echo ""
	echo "ERROR: SOPC_KIT_NIOS2 environmental variable must be set"
	echo ""
	exit 1
}

# has the application Makefile already been created?
[ -f ./Makefile ] && {
	set +x
	echo ""
	echo "ERROR: Application Makefile already exists.  Delete Makefile to recreate."
	echo ""
	exit 1
}

# is the BSP project built?
[ -f "${BSP_DIR:?}/public.mk" ] || {
	pushd "${BSP_DIR:?}" >> /dev/null
	./create-this-bsp || {
		set +x
		echo "create-this-bsp failed"
		exit 1
	}
	popd >> /dev/null
}

# create the reset modules assignments header file
sopcinfo2swinfo \
	--input="${QUARTUS_PROJECT_DIR:?}/test_sys.sopcinfo" \
	--output=test_sys.swinfo || {
		set +x
		echo "sopcinfo2swinfo failed"
		exit 1
	}

../../scripts/extract_swinfo.sh test_sys.swinfo || {
	set +x
	echo "extract_swinfo.sh failed"
	exit 1
}

# create the application project Makefile
nios2-app-generate-makefile \
	--bsp-dir "${BSP_DIR:?}" \
	${NIOS2_APP_GEN_ARGS:?} || {
		set +x
		echo "nios2-app-generate-makefile failed"
		exit 1
	}

# build application project
make || {
	set +x
	echo "make failed"
	exit 1
}

# create the meminit file for the onchip RAM
make mem_init_generate || {
	set +x
	echo "make mem_init_generate failed"
	exit 1
}

set +x

exit 0

